### PR TITLE
Fixed bug with expiresAfter(null)

### LINKED ISSUE #1: Potential issue
Just got the following in production:

```
Exception: DateInterval::__construct(): Unknown or bad format (PTS) in .../vendor/madewithlove/illuminate-psr-cache-bridge/src/Laravel/CacheItem.php:101
Stack trace:
#0 .../vendor/madewithlove/illuminate-psr-cache-bridge/src/Laravel/CacheItem.php(101): DateInterval->__construct('PTS')
#1 .../vendor/php-http/cache-plugin/src/CachePlugin.php(90): Madewithlove\IlluminatePsrCacheBridge\Laravel\CacheItem->expiresAfter(NULL)
#2 .../vendor/php-http/promise/src/FulfilledPromise.php(35): Http\Client\Common\Plugin\CachePlugin->Http\Client\Common\Plugin\{closure}(Object(GuzzleHttp\Psr7\Response))
#3 .../vendor/php-http/cache-plugin/src/CachePlugin.php(95): Http\Promise\FulfilledPromise->then(Object(Closure))
#4 .../vendor/php-http/client-common/src/PluginClient.php(155): Http\Client\Common\Plugin\CachePlugin-
```

I've not looked into this yet to determine if the other library is calling this one incorrectly, or if there's a bug here. Just giving you an early heads up.

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix #1 and replace #2

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Look at the interface: https://github.com/php-fig/cache/blob/master/src/CacheItemInterface.php#L95. It forbids passing `null` as a parameter.

**Comment by Nyholm** [comment]
https://github.com/php-fig/cache/blob/master/src/CacheItemInterface.php#L98

**Comment by GrahamCampbell** [comment]
FFS, the phpdoc is inconsistent with itself then.

**Comment by Nyholm** [comment]
> FFS, the phpdoc is inconsistent with itself then.

Yes, it is. I've found quite a few of those.

**Comment by GrahamCampbell** [comment]
https://github.com/php-fig/cache/pull/7

**Comment by GrahamCampbell** [comment]
👍

**Comment by Nyholm** [comment]
Hey. Any change to get this PR merged?

**Pull request merged**
