### PR TITLE
Moved illuminate/cache to requirements

### PR DESCRIPTION
**Pull request by Nyholm**
This is a blocker for https://github.com/php-cache/integration-tests/pull/60

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👎 You need to only have the contracts repo. You can choose any implementation you want. Unfortunately, laravel doesn't provide virtual packages to ensure you have one.

**Comment by Nyholm** [comment]
Excuse my ignorance. Doesn't

**Comment by Nyholm** [comment]
Excuse my ignorance. Doesn't `Illuminate\Contracts\Cache\Repository` live in the `illuminate/cache`? 

https://github.com/madewithlove/illuminate-psr-cache-bridge/blob/1.0.1/src/Laravel/CacheItemPool.php#L26

**Comment by GrahamCampbell** [comment]
> Doesn't Illuminate\Contracts\Cache\Repository live in the illuminate/cache?

No, it's in the contracts repo. Only `Illuminate\Cache\Repository` in in the cache repo. :)

**Comment by GrahamCampbell** [comment]
Maybe the cache package should be added to this package's suggest list though?

**Comment by Nyholm** [comment]
I see, You are correct. I'll make sure to update the integration tests PR. 

Thank you!

**Pull request closed without merging**
