### PR TITLE
Cast the time to an integer to be on the safe side

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Comes after https://github.com/madewithlove/illuminate-psr-cache-bridge/issues/1.

### CODE REVIEW

**Comment by Nyholm** [comment]
:-1: since this violates the specification. Null is a valid argument.

**Comment by GrahamCampbell** [comment]
No it's not? The spec doesn't allow null?

**Comment by Nyholm** [comment]
The spec do allow null. See my comment here: https://github.com/php-http/cache-plugin/pull/10#issuecomment-236793275

**Comment by GrahamCampbell** [comment]
Ah, right. Stupid spec being inconsistent with itself.

**Comment by GrahamCampbell** [comment]
Thanks. :)

**Pull request closed without merging**
